<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>asynchronous-ask17</title>
    <style>
    body {
        background-color: tan;
        margin: 0;
        font-family: Verdana, sans-serif;
    }

    .title {
        color: red;
        text-align: center;
        font-weight:700;
    }

    .task{
        width: 52%;
        padding: 15px 25px;
        color: navy;
        background-color: #e2e2e2;
        margin: 35px auto;
    }

    .code-ex {
        width: 60%;
        font-family: sans-serif;
        background-color: #bebebe;
        font-size: large;
        padding-left: 15px;
        margin: 0 auto;
    }

    p {
        width: 80%;
        margin: 0 auto;
    }
    </style>
</head>
<body>

    <h2 class="title">Асинхронний код, задача</h2>

    <h4 class="task">1. Створіть об'єкт promise;<br>
      2. Переведіть promise в стан fulfilled з результатом 'some result' при цьому<br>
      3. Використовуючи 'setTimeout' в якості асинхронної операції, виведіть через<br>
      &nbsp;&nbsp;&nbsp;&nbsp;1 секунду у консоль успішно-завершину операцію «Fulfilled: some result»;<br>
      4. Також, покажіть код якщо проміс завершиться з помилкою;<br>
    </h4>
    <br>

    <p><b>Рішення:</b></p>
    <br>

    <p class="code-ex">
      <code>
        <br>
        'use strict';<br>
        <br>
        // Створюємо об'єкт promise з допомогою конструктора promis:<br>
        let promise = new Promise((resolve, reject) => {<br>
        &nbsp;&nbsp;&nbsp;setTimeout(() => {<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// переводимо проміс в стан fulfilled з результатом 'some result'<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolve('some result');<br>
        &nbsp;&nbsp;&nbsp;}, 1000);<br>
        });<br>
        <br>
        // Використовуючи метод <i>.then</i> ми можемо навісити обробники чи на успішний результат чи помилку<br>
        promise<br>
        &nbsp;&nbsp;&nbsp;.then(<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result => {<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// перша функція-обробник - запуститься при виклику resolve<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log("Fulfilled: " + result); // some result - аргумент resolve<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;error => {<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// друга функція - запуститься при виклику reject<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log("Rejected: " + error); // error - аргумент reject<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
        &nbsp;&nbsp;&nbsp;);<br>
        <br>
      </code>
    </p>
    <br>

    <script>
      'use strict';

      let promise = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve("some result");
        }, 1000);
      });

      promise
        .then(
          result => {
            console.log("Fulfilled: " + result); // Fulfilled: some result
          },
          error => {
            console.log("Rejected: " + error);
          }
        );
    </script>

    <p>У разі, якщо в <i>setTimeout</i> замість <i>resolve('result')</i> був би виклик <i>reject('error')</i>, то вивелось би 
      «Rejected: error».<br>
      Хоча, як правило, якщо при виконанні виникла проблема, то <i>reject</i> викликають з об'єктом помилки <em>new Error</em>:
    </p>
    <br>

    <p class="code-ex">
      <code>
        'use strict';<br>
      <br>
      // цей promise завершится з помилкою через 1 секунду<br>
      var promise = new Promise((resolve, reject) => {<br>
        &nbsp;&nbsp;&nbsp;setTimeout(() => {<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>reject(new Error("час вже вийшов!"))</b>;<br>
        &nbsp;&nbsp;&nbsp;}, 1000);<br>
      });<br>
      <br>
      promise<br>
      &nbsp;&nbsp;&nbsp;.then(<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result => console.log("Fulfilled: " + result),<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;error => console.log("Rejected: " + error.message) // Rejected: час вже вийшов!<br>
      &nbsp;&nbsp;&nbsp;);<br>
      </code>
    </p>
    <br>
    <p>Звичайно, замість setTimeout всередині функції проміса може бути і запит на сервер і очікування
      введення користувачем чи інший асинхронний процес. Головне, щоби по своєму завершенню він
      викликав resolve або reject, які вже передадуть результат обробникам.
    </p><br><br>
</body>

</html>